export const CHANGE_SORT_ORDER = 'CHANGE_SORT_ORDER';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const MULTIPLE_ADD_TO_CART = 'MULTIPLE_ADD_TO_CART';
export const INCREMENT_CART_ITEM_QUANTITY = 'INCREMENT_CART_ITEM_QUANTITY';
export const DECREMENT_CART_ITEM_QUANTITY = 'DECREMENT_CART_ITEM_QUANTITY';

export const ASYNC_GET_PRODUCTS: string = 'ASYNC_GET_PRODUCTS';
export const ASYNC_GET_PRODUCTS_ERROR: string = 'ASYNC_GET_PRODUCTS_ERROR';
export const ASYNC_GET_PRODUCTS_SUCCESS: string = 'ASYNC_GET_PRODUCTS_SUCCESS';
