export const ADD_TO_CART = 'ADD_TO_CART'

export const ASYNC_GET_PRODUCTS: string = 'ASYNC_GET_PRODUCTS';
export const ASYNC_GET_PRODUCTS_ERROR: string = 'ASYNC_GET_PRODUCTS_ERROR';
export const ASYNC_GET_PRODUCTS_SUCCESS: string = 'ASYNC_GET_PRODUCTS_SUCCESS';
