export const ASYNC_GET_TICKETS: string = 'ASYNC_GET_TICKETS';
export const ASYNC_GET_TICKETS_ERROR: string = 'ASYNC_GET_TICKETS_ERROR';
export const ASYNC_GET_TICKETS_SUCCESS: string = 'ASYNC_GET_TICKETS_SUCCESS';